name: "GitHub Action - CI"
description: "A GitHub Action integrated with CircleCI and GitHub."
inputs:
  task:
    description: "The name of a task to run."
    required: true
  repository:
    description: "The GitHub repository to use."
    required: true
  recent:
    description: "A time delta to use for time comparisons."
    required: false
  token:
    description: "A token to use the CI provider's API."
    required: false
    default: ""
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.task }}
    - ${{ inputs.repository }}
    - --recent
    - ${{ inputs.recent }}
    - --token
    - ${{ inputs.token }}
