name: "CircleCI API"
description: ""
inputs:
  task:
    description: ""
    required: true
  repository:
    description: ""
    required: true
  circle-token:
    description: ""
    required: false
    default: ""
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.task }}
    - ${{ inputs.repository }}
    - --recent
    - ${{ inputs.recent }}
    - --circle-token
    - ${{ inputs.circle-token }}
