on: push

name: CircleCI Scheduler
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/circleci-api
        with:
          task: latest_workflow_status
          repository: facebook/react # placeholder
      - if: success()
        name: Checkout Featuretools
        uses: actions/checkout@v2
        with:
          repository: featurelabs/featuretools
      - name: Check for Recent Commit
        run: |
          import subprocess
          from datetime import datetime, timedelta

          recent = eval('timedelta(%s)' % 'year=1')
          args = r"git log -1 --format=%cd --date=unix".split()
          timestamp = int(subprocess.check_output(args))
          latest_commit_time = datetime.utcfromtimestamp(timestamp)

          elapsed = datetime.utcnow() - latest_commit_time
          assert elapsed <= recent, 'latest commit was not recent'
        shell: python
      - if: success()
        name: Trigger CircleCI
        run: echo success