on: push

name: Integration Tests
jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Requirements
        run: make install
      - name: Run Lint Tests
        run: make lint-tests
      - name: Run Unit Tests
        run: make CIRCLE_TOKEN=${{ secrets.CIRCLE_TOKEN }} unit-tests
